---
title: 'Project 1: Exploratory Data Analysis'
author: "Lauren Hart, lnh766"
date: '10/1/2020'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="lauren-hart-lnh766" class="section level1">
<h1>Lauren Hart, lnh766</h1>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><em>In this project, two datasets are included that correspond to two different North American tree species found in the same four various ForestGeo plots. The species are </em>Acer rubra<em>, the red maple tree (ACERRU), and </em>Quercus alba<em>, the red oak tree (QUERRU). I am interested in these datasets because I would like to analyze the chemical similarities and differences intraspecifically across a spatial gradient. I would also like to analyze inter-specific chemical similarities and differences in the same forest plots to better understand and hypothesize reasonings for for chemical evolution due to herbivory pressures. We hypothesize to see the same species to be more chemically similar, but as they are more spaced out, they should become more different. We expect to see different species that live near each other to be less chemically similar as they must outcompete each other for survival, and different species that do not live in the same plots to be more chemically similar. We will quantify chemical similarity using chemical richness, corresponding to the area of the compound, and chemical abundance, corresponding to the number of compounds each species produces. The immature leaves of these trees were sampled by field scientists at the Michigan, Tyson, Smithsonian Conservation Biology Institute, and Smithsonian Environmental Research Center plots found in North America. These leaves were then put through methanol extraction and processed through orbitrap mass spectrometry. The datasets are mass spectrometry ionization and fragmentation data that has been processed and mined using the program </em>Compound Discover<em>. Each dataset contains many samples from each plot, and each sample has its' own column within the dataset with its' areas corresponding to each compound below it as a value.</em></p>
<p><em>The original datasets include many variables although not all of them are neccesary for this research. The datasets include the <code>Name</code> of the compounds found within the species and their <code>formula</code> and <code>Molecular.Weight</code>. They include mass spectrometry specific data such as the ionization <code>area</code> which appears under each sample ran in the dataset as well as the retention time within the orbitrap, <code>RT..min.</code>. The </em>Compound Discover* program mines from four different databases of compounds and produces a response ranging from <code>Full Match</code> to <code>not a match</code> as a value under one of the four column names that contain <code>Annotation...</code>. Although there are many other columns in the datasets, they are not relevant to the statistical work that will be done in this project. If interested, you can visit the <em>Compound Discover</em> website to review their manual and better understand the dataset variables. <a href="https://assets.thermofisher.com/TFS-Assets/CMD/manuals/man-xcali-98120-compound-discoverer-user-manxcali98120-en.pdf" class="uri">https://assets.thermofisher.com/TFS-Assets/CMD/manuals/man-xcali-98120-compound-discoverer-user-manxcali98120-en.pdf</a>*</p>
<p><em>First, we must read the .csv files into the environment.</em></p>
<pre class="r"><code>## Read .csv files into the environment
library(tidyverse)
ACERRU_compounds &lt;- read.table(&quot;ACERRU_compounds.csv&quot;, header = TRUE)
QUERRU_compounds &lt;- read.table(&quot;QUERRU_compounds.csv&quot;, header = TRUE)</code></pre>
</div>
<div id="tidying-the-data" class="section level2">
<h2>1. TIDYING THE DATA</h2>
</div>
<div id="acerru-tidying" class="section level2">
<h2>ACERRU TIDYING</h2>
<p><em>Next, we must tidy the data for ACERRU. First, the dataset must be converted into a dataframe. </em></p>
<pre class="r"><code>## ACERRU- red maple (Acer Rubra)
ACERRU_project &lt;- as.data.frame(ACERRU_compounds)</code></pre>
<p><em>Next, the rows necessary for the dataset must be selected. We need to include all of the samples, the compound name and molecular weight, the area and retention time for each compound, and the four annotation columns to sum up the amount of full matches each compound had. Next, the data needs to be pivoted longer so that area and sample ID are their own columns.</em></p>
<pre class="r"><code>## select rows to include in data frame and pivot longer
ACERRU_project &lt;- ACERRU_compounds %&gt;% select(2, 4:7, 9:10, 19:48) %&gt;% 
    mutate(Species = &quot;ACERRU&quot;) %&gt;% pivot_longer(8:37, names_to = &quot;SampleID&quot;, 
    values_to = &quot;Area&quot;)</code></pre>
<p><em>Next, the plots need to have uniform naming. In the blank files, some of them are slightly different and they must be seperated correctly to be in their own column. We use separate after the plots are uniformly named so that plot can have its own column.</em></p>
<pre class="r"><code>## rename plots that have incorrect plot name
ACERRU_project &lt;- ACERRU_project %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SERC&quot;, &quot;SR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SCBI&quot;, &quot;SB&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;TRB&quot;, &quot;TR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;UMB&quot;, &quot;UM&quot;))

## plot in its own column
ACERRU_project &lt;- ACERRU_project %&gt;% separate(SampleID, into = c(NA, 
    &quot;temp2&quot;), sep = 6, remove = F) %&gt;% separate(temp2, into = c(&quot;Plot&quot;, 
    NA), sep = 2)</code></pre>
<p><em>Lastly, we want to create a row that has the sum, for each sampleID and compound, of full matches from each database. We did this below, and then removed the four annotation columns so that we had just one numeric variable that adds up the total full matches for that combination of sample ID and compound.</em></p>
<pre class="r"><code># row with sum of full matches for that sampleID and name
ACERRU_project &lt;- ACERRU_project %&gt;% group_by(Name, SampleID) %&gt;% 
    mutate(Full_Matches = sum(c(Annotation.Source..Predicted.Compositions == 
        &quot;Full match&quot;, Annotation.Source..mzCloud.Search == &quot;Full match&quot;, 
        Annotation.Source..Metabolika.Search == &quot;Full match&quot;, 
        Annotation.Source..ChemSpider.Search == &quot;Full match&quot;)))

## remove rows for Annotations
ACERRU_project &lt;- ACERRU_project %&gt;% subset(select = -c(2:5))</code></pre>
<p><em>All of this code was eventually ran together to produce a dataset that has 8 variables and 15,236 rows after I exlcuded the blanks in the final two filter functions used in this code. For clarification, the blank data was excldued from the rest of the analyses because the data has already been filtered and only the compounds with ionization areas above the blank values were kept in the dataframe, thus, the blank data does not need to be analyzed again with the real QUERRU and ACERRU data. We ran glimpse at the end of the code to understand what we had left and to review our data. </em></p>
<pre class="r"><code>## ALL ran together
ACERRU_project &lt;- ACERRU_compounds %&gt;% select(2, 4:7, 9:10, 19:48) %&gt;% 
    mutate(Species = &quot;ACERRU&quot;) %&gt;% pivot_longer(8:37, names_to = &quot;SampleID&quot;, 
    values_to = &quot;Area&quot;) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SERC&quot;, &quot;SR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SCBI&quot;, &quot;SB&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;TRB&quot;, &quot;TR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;UMB&quot;, &quot;UM&quot;)) %&gt;% separate(SampleID, into = c(NA, &quot;temp2&quot;), 
    sep = 6, remove = F) %&gt;% separate(temp2, into = c(&quot;Plot&quot;, 
    NA), sep = 2) %&gt;% group_by(Name, SampleID) %&gt;% mutate(Full_Matches = sum(c(Annotation.Source..Predicted.Compositions == 
    &quot;Full match&quot;, Annotation.Source..mzCloud.Search == &quot;Full match&quot;, 
    Annotation.Source..Metabolika.Search == &quot;Full match&quot;, Annotation.Source..ChemSpider.Search == 
        &quot;Full match&quot;))) %&gt;% subset(select = -c(2:5)) %&gt;% filter(!str_detect(SampleID, 
    &quot;Blank&quot;)) %&gt;% filter(!str_detect(SampleID, &quot;BLANK&quot;)) %&gt;% 
    ungroup()

glimpse(ACERRU_project)</code></pre>
<pre><code>## Rows: 15,236
## Columns: 8
## $ Name             &lt;fct&gt; Erucamide, Erucamide, Erucamide, Erucamide, Erucamid…
## $ Molecular.Weight &lt;dbl&gt; 337.3341, 337.3341, 337.3341, 337.3341, 337.3341, 33…
## $ RT..min.         &lt;dbl&gt; 17.215, 17.215, 17.215, 17.215, 17.215, 17.215, 17.2…
## $ Species          &lt;chr&gt; &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;A…
## $ SampleID         &lt;chr&gt; &quot;Area..SB00054_ACERRU.raw..F1.&quot;, &quot;Area..SB00061_ACER…
## $ Plot             &lt;chr&gt; &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SR&quot;, &quot;SR&quot;, &quot;SR&quot;…
## $ Area             &lt;dbl&gt; 2235531390, 1670624499, 2756611323, 2301396767, 2561…
## $ Full_Matches     &lt;int&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…</code></pre>
</div>
<div id="querru-tidying" class="section level2">
<h2>QUERRU TIDYING</h2>
<p><em>Next, we must tidy the data for ACERRU. First, the dataset must be converted into a dataframe. </em></p>
<pre class="r"><code># QUERRU- red oak (Quercus Alba)
QUERRU_project &lt;- as.data.frame(QUERRU_compounds)</code></pre>
<p><em>Next, the rows necessary for the dataset must be selected. We need to include all of the samples, the compound name and molecular weight, the area and retention time for each compound, and the four annotation columns to sum up the amount of full matches each compound had. Next, the data needs to be pivoted longer so that area and sample ID are their own columns.</em></p>
<pre class="r"><code># select rows and pivot longer
QUERRU_project &lt;- QUERRU_compounds %&gt;% select(2, 4:7, 9:10, 19:55) %&gt;% 
    mutate(Species = &quot;QUERRU&quot;) %&gt;% pivot_longer(8:44, names_to = &quot;SampleID&quot;, 
    values_to = &quot;Area&quot;)</code></pre>
<p><em>Next, the plots need to have uniform naming. In the blank files, some of them are slightly different and they must be seperated correctly to be in their own column. We use separate after the plots are uniformly named so that plot can have its own column.</em></p>
<pre class="r"><code># rename incorrect plot names
QUERRU_project &lt;- QUERRU_project %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SERC&quot;, &quot;SR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SCBI&quot;, &quot;SB&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;TRB&quot;, &quot;TR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;UMB&quot;, &quot;UM&quot;))

# new column for plot names
QUERRU_project &lt;- QUERRU_project %&gt;% separate(SampleID, into = c(NA, 
    &quot;temp2&quot;), sep = 6, remove = F) %&gt;% separate(temp2, into = c(&quot;Plot&quot;, 
    NA), sep = 2)</code></pre>
<p><em>Lastly, we want to create a row that has the sum, for each sampleID and compound, of full matches from each database. We did this below, and then removed the four annotation columns so that we had just one numeric variable that adds up the total full matches for that combination of sample ID and compound.</em></p>
<pre class="r"><code># Sum full matches in new column
QUERRU_project &lt;- QUERRU_project %&gt;% group_by(Name, SampleID) %&gt;% 
    mutate(Full_Matches = sum(c(Annotation.Source..Predicted.Compositions == 
        &quot;Full match&quot;, Annotation.Source..mzCloud.Search == &quot;Full match&quot;, 
        Annotation.Source..Metabolika.Search == &quot;Full match&quot;, 
        Annotation.Source..ChemSpider.Search == &quot;Full match&quot;))) %&gt;% 
    subset(select = -c(2:5))</code></pre>
<p><em>All of this code was eventually ran together to produce a dataset that has 8 variables and 18,612 rows after I excluded the blank data from the data. We ran glimpse at the end of the code to understand what we had left and to review our data. </em></p>
<pre class="r"><code>## All together
QUERRU_project &lt;- QUERRU_compounds %&gt;% select(2, 4:7, 9:10, 19:55) %&gt;% 
    mutate(Species = &quot;QUERRU&quot;) %&gt;% pivot_longer(8:44, names_to = &quot;SampleID&quot;, 
    values_to = &quot;Area&quot;) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SERC&quot;, &quot;SR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;SCBI&quot;, &quot;SB&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;TRB&quot;, &quot;TR&quot;)) %&gt;% mutate(SampleID = str_replace(SampleID, 
    &quot;UMB&quot;, &quot;UM&quot;)) %&gt;% separate(SampleID, into = c(NA, &quot;temp2&quot;), 
    sep = 6, remove = F) %&gt;% separate(temp2, into = c(&quot;Plot&quot;, 
    NA), sep = 2) %&gt;% group_by(Name, SampleID) %&gt;% mutate(Full_Matches = sum(c(Annotation.Source..Predicted.Compositions == 
    &quot;Full match&quot;, Annotation.Source..mzCloud.Search == &quot;Full match&quot;, 
    Annotation.Source..Metabolika.Search == &quot;Full match&quot;, Annotation.Source..ChemSpider.Search == 
        &quot;Full match&quot;))) %&gt;% subset(select = -c(2:5)) %&gt;% filter(!str_detect(SampleID, 
    &quot;Blank&quot;)) %&gt;% filter(!str_detect(SampleID, &quot;BLANK&quot;)) %&gt;% 
    ungroup()

glimpse(QUERRU_project)</code></pre>
<pre><code>## Rows: 18,612
## Columns: 8
## $ Name             &lt;fct&gt; Bis(methylbenzylidene)sorbitol, Bis(methylbenzyliden…
## $ Molecular.Weight &lt;dbl&gt; 386.1727, 386.1727, 386.1727, 386.1727, 386.1727, 38…
## $ RT..min.         &lt;dbl&gt; 11.968, 11.968, 11.968, 11.968, 11.968, 11.968, 11.9…
## $ Species          &lt;chr&gt; &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;Q…
## $ SampleID         &lt;chr&gt; &quot;Area..SB00114_QUERRU_actual.raw..F1.&quot;, &quot;Area..SB001…
## $ Plot             &lt;chr&gt; &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;…
## $ Area             &lt;dbl&gt; 1667380538, 1780540427, 1341439436, 1520274599, 1146…
## $ Full_Matches     &lt;int&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…</code></pre>
</div>
<div id="joining-the-data" class="section level2">
<h2>2. JOINING THE DATA</h2>
<p><em>In the case of this data, the dataset for each species has the same variables. I purposely named the variables the same thing for each species so that they could eventually be stacked. They could be joined with the common variable of plot, but this would lead to duplicated rows and trouble with plotting in the future. For the sake of our analyses and figures, stacking the data using <code>bind_rows</code> was the best choice to join ACERRU and QUERRU data. The ACERRU dataframe had 15,236 observations of 8 variables, and the QUERRU dataframe had 18,612 observations of the same 8 variables. After the dataframes were stacked, the final dataframe, <code>AQ_Joined</code> has 33,848 observations of the same 8 variables. No rows of data were dropped during the join because they are all vital to the data to calculate summary statistics and plots. <code>AQ_Joined</code> will be used for the remainder of the analyses, except for the correlation matrix where I will do a <code>full_join</code> to the data. </em></p>
<pre class="r"><code># bind rows together by stacking them:
AQ_Joined &lt;- bind_rows(QUERRU_project, ACERRU_project) %&gt;% rename(Full.Match = Full_Matches)
AQ_Joined</code></pre>
<pre><code>## # A tibble: 33,848 x 8
##    Name     Molecular.Weight RT..min. Species SampleID   Plot    Area Full.Match
##    &lt;fct&gt;               &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;  &lt;dbl&gt;      &lt;int&gt;
##  1 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.67e9          4
##  2 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.78e9          4
##  3 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.34e9          4
##  4 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.52e9          4
##  5 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.15e9          4
##  6 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.39e9          4
##  7 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.73e9          4
##  8 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.10e9          4
##  9 Bis(met…             386.     12.0 QUERRU  Area..SB0… SB    1.57e9          4
## 10 Bis(met…             386.     12.0 QUERRU  Area..SBP… SB    1.48e9          4
## # … with 33,838 more rows</code></pre>
</div>
<div id="wranglingsummary-statistics" class="section level2">
<h2>3. WRANGLING/SUMMARY STATISTICS</h2>
<p><em>In order to better understand the relationships that are present between ACERRU and QUERRU, as well as how they are similar and different to their own conspecifics in different plots, summary statistics need to be calculated for different groupings of variables. I decided to summarize each numeric variable without a grouping, and then summarized each numeric variable when grouped by plot and species. I used mean, standard deviation, minimum, maximum, and the number of total distinct values in each response variable to summarize the variables. I used mutate in the reshaping of my data to create the number of full matches column that summed the number of full matches for each compound and sample ID combination from each database. Also, I used filter in order to exclude the blanks from my joined dataframe. Lastly, a correlation matrix was created for the numeric variables in the dataset after the data was reorganized to make x numeric. All of these summary statistics were then tidied into a table.</em></p>
<pre class="r"><code># number of distinct values, mean, standard deviation,
# minimum, and maxium for each numeric variable in the joined
# dataset in a table:
table_for_numerics &lt;- AQ_Joined %&gt;% select(is.numeric) %&gt;% summarize_all(c(n = n_distinct, 
    mean = mean, sd = sd, mininmum = min, maximum = max)) %&gt;% 
    pivot_longer(3:20, names_to = &quot;stat&quot;, values_to = &quot;value&quot;) %&gt;% 
    separate(stat, into = c(&quot;variable&quot;, &quot;statistic&quot;), sep = &quot;_&quot;) %&gt;% 
    pivot_wider(names_from = statistic, values_from = value)
table_for_numerics %&gt;% filter(variable == &quot;Area&quot;) %&gt;% arrange(sd)  #see lowest to highest sd for area</code></pre>
<pre><code>## # A tibble: 1 x 8
##   Molecular.Weight… RT..min._n variable     n     mean      sd mininmum  maximum
##               &lt;int&gt;      &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1              1077        997 Area     33141   6.64e7  5.03e8    1020.  2.96e10</code></pre>
<pre class="r"><code>table_for_numerics %&gt;% filter(variable == &quot;Area&quot;) %&gt;% arrange(-sd)  #see highest to lowest sd for area</code></pre>
<pre><code>## # A tibble: 1 x 8
##   Molecular.Weight… RT..min._n variable     n     mean      sd mininmum  maximum
##               &lt;int&gt;      &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1              1077        997 Area     33141   6.64e7  5.03e8    1020.  2.96e10</code></pre>
<pre class="r"><code># grouping by plot and species I calculated: the number of
# distinct values, mean, standard deviation, minimum, and
# maximum values and made the summary statistics into a
# table:
table_for_groupings &lt;- AQ_Joined %&gt;% group_by(Species, Plot) %&gt;% 
    summarize_if(is.numeric, c(n = n_distinct, mean = mean, sd = sd, 
        minimum = min, maximum = max)) %&gt;% pivot_longer(3:22, 
    names_to = &quot;stat&quot;, values_to = &quot;value&quot;) %&gt;% separate(stat, 
    into = c(&quot;variable&quot;, &quot;statistic&quot;), sep = &quot;_&quot;) %&gt;% pivot_wider(names_from = statistic, 
    values_from = value)
table_for_groupings %&gt;% filter(variable == &quot;Area&quot;) %&gt;% arrange(n)  #lowest to highest amount of distinct values for area</code></pre>
<pre><code>## # A tibble: 8 x 8
## # Groups:   Species [2]
##   Species Plot  variable     n       mean         sd minimum      maximum
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;
## 1 QUERRU  SR    Area      2808  73977308. 568867168.  10979. 15936130689.
## 2 QUERRU  TR    Area      3371  55993990. 312701904.  10923.  7162145119.
## 3 ACERRU  SB    Area      3491 101009547. 681299344.  10555. 16728675137.
## 4 ACERRU  SR    Area      3499 120100425. 879979347.   9078. 29637964533.
## 5 ACERRU  TR    Area      3504 105926047. 696550273.  16907. 17488980560.
## 6 ACERRU  UM    Area      4668  45746725. 307210696.   3016.  8201302527.
## 7 QUERRU  SB    Area      5621  36344475. 188942313.   1020.  5274232816.
## 8 QUERRU  UM    Area      6179  41415630. 297991404.   4663.  7360720546.</code></pre>
<pre class="r"><code>table_for_groupings %&gt;% filter(variable == &quot;Area&quot;) %&gt;% arrange(-n)  #highest to lowest amount of distinct values for area </code></pre>
<pre><code>## # A tibble: 8 x 8
## # Groups:   Species [2]
##   Species Plot  variable     n       mean         sd minimum      maximum
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;
## 1 QUERRU  UM    Area      6179  41415630. 297991404.   4663.  7360720546.
## 2 QUERRU  SB    Area      5621  36344475. 188942313.   1020.  5274232816.
## 3 ACERRU  UM    Area      4668  45746725. 307210696.   3016.  8201302527.
## 4 ACERRU  TR    Area      3504 105926047. 696550273.  16907. 17488980560.
## 5 ACERRU  SR    Area      3499 120100425. 879979347.   9078. 29637964533.
## 6 ACERRU  SB    Area      3491 101009547. 681299344.  10555. 16728675137.
## 7 QUERRU  TR    Area      3371  55993990. 312701904.  10923.  7162145119.
## 8 QUERRU  SR    Area      2808  73977308. 568867168.  10979. 15936130689.</code></pre>
<pre class="r"><code># retidying of data to create a correlation matrix and
# eventually a correlation heat map, used a full join to
# include all of the data in the project:
NewJoin_AQ &lt;- full_join(ACERRU_project, QUERRU_project, by = &quot;Plot&quot;) %&gt;% 
    rename(ACERRU_Compounds = Name.x, ACERRU_MW = Molecular.Weight.x, 
        ACERRU_RT = RT..min..x, Species_A = Species.x, ACERRU_ID = SampleID.x, 
        ACERRU_area = Area.x, ACERRU_FullMatch = Full_Matches.x, 
        QUERRU_Compounds = Name.y, QUERRU_MW = Molecular.Weight.y, 
        QUERRU_RT = RT..min..y, Species_Q = Species.y, QUERRU_ID = SampleID.y, 
        QUERRU_area = Area.y, QUERRU_FullMatch = Full_Matches.y) %&gt;% 
    relocate(Plot, .after = ACERRU_FullMatch)
glimpse(NewJoin_AQ)</code></pre>
<pre><code>## Rows: 73,371,888
## Columns: 15
## $ ACERRU_Compounds &lt;fct&gt; Erucamide, Erucamide, Erucamide, Erucamide, Erucamid…
## $ ACERRU_MW        &lt;dbl&gt; 337.3341, 337.3341, 337.3341, 337.3341, 337.3341, 33…
## $ ACERRU_RT        &lt;dbl&gt; 17.215, 17.215, 17.215, 17.215, 17.215, 17.215, 17.2…
## $ Species_A        &lt;chr&gt; &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;ACERRU&quot;, &quot;A…
## $ ACERRU_ID        &lt;chr&gt; &quot;Area..SB00054_ACERRU.raw..F1.&quot;, &quot;Area..SB00054_ACER…
## $ ACERRU_area      &lt;dbl&gt; 2235531390, 2235531390, 2235531390, 2235531390, 2235…
## $ ACERRU_FullMatch &lt;int&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…
## $ Plot             &lt;chr&gt; &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;, &quot;SB&quot;…
## $ QUERRU_Compounds &lt;fct&gt; &quot;Bis(methylbenzylidene)sorbitol&quot;, &quot;Bis(methylbenzyli…
## $ QUERRU_MW        &lt;dbl&gt; 386.1727, 386.1727, 386.1727, 386.1727, 386.1727, 38…
## $ QUERRU_RT        &lt;dbl&gt; 11.968, 11.968, 11.968, 11.968, 11.968, 11.968, 11.9…
## $ Species_Q        &lt;chr&gt; &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;QUERRU&quot;, &quot;Q…
## $ QUERRU_ID        &lt;chr&gt; &quot;Area..SB00114_QUERRU_actual.raw..F1.&quot;, &quot;Area..SB001…
## $ QUERRU_area      &lt;dbl&gt; 1667380538, 1780540427, 1341439436, 1520274599, 1146…
## $ QUERRU_FullMatch &lt;int&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2…</code></pre>
<pre class="r"><code># creating a correlation matrix:
cormatAQ &lt;- NewJoin_AQ %&gt;% na.omit() %&gt;% select(is.numeric) %&gt;% 
    cor(use = &quot;pair&quot;)</code></pre>
<p><em>The summary of statistics above are just a few of the ways we could analyze the data. By computing the number of distinct values, mean, standard deviation, minimum, and maximum values for each numeric variable, we can get a better idea of the spread and characteristics of the data. For the compound mean area, MIPC had the lowest area in QUERRU and Erucamide had the highest area in both QUERRU and ACERRU. Erucamide also had the largest standard deviation in both ACERRU and QUERRU, and 2,3-Bis[(9E)-9-octadecenoyloxy]propyl-2-(trimethylammonio)ethylphosphat had the lowest standard deviation when in ACERRU. The rest of these summary statistics for each compound can be seen from the table <code>table_for_numerics</code> and can be manipulated using the filter and arrange dplyr functions as I did above in the 2 examples on lines 141 and 142. </em></p>
<p><em>I then calculated the numeric summary statistics after grouping the compounds by species and plot. I found that QUERRU in the SCBI (SB) plot had the lowest mean Area and ACERRU in the SERC (SR) plot had the highest mean , maximum, and standard deviation for area. The QUERRU at the Michigan plot (UM) had the most distinct compounds, and the QUERRU at the SERC (SR) plot had the least amount of compounds, with a large difference in between (aout 4,000). The rest of the grouped summary statistics can be observed in the table and rearranged using the filter and arrange dplyr functions as I demonstrated with two exmaples in lines 146 and 147. Lastly, the correlation matrix shows low correlations for every variable combination.</em></p>
</div>
<div id="visualizing-the-data" class="section level2">
<h2>4. VISUALIZING THE DATA</h2>
<ul>
<li><em>In this section, I will plot different variables against each other in the dataset in order to visualize the data better. These are just a handful of possible visualizations that we can make in ggplot for the purpose of figures. </em></li>
</ul>
<p><em>Correlation heat map</em></p>
<pre class="r"><code># tidy the correlation matrix:
tidycormatAQ &lt;- cormatAQ %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;Variable_1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;Variable_2&quot;, values_to = &quot;correlation&quot;)
# make the correlation matrix:
tidycormatAQ %&gt;% ggplot(aes(Variable_1, Variable_2, fill = correlation)) + 
    geom_tile() + scale_fill_gradient2(low = &quot;light blue&quot;, mid = &quot;turquoise&quot;, 
    high = &quot;purple&quot;) + geom_text(aes(label = round(correlation, 
    2)), color = &quot;white&quot;, size = 4) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + coord_fixed() + ggtitle(&quot;Correlation Heat Map&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>As seen in the correlation matrix above, there is a diaganol line of purple correlations that are equal to one, being the correlations between each variable and themselves. The next highest correlations are between retention time and molecular weight being 0.51 for each species. This makes sense because molecular weight is used in calculating retention time in mass spectrometry. There are not any other high correlations, nor are there any correlations between variables of different species. </em></p>
<p><em>Grouped Barplot</em></p>
<pre class="r"><code>AQ_Joined %&gt;% ggplot(aes(x = Plot, y = Area, fill = Species)) + 
    geom_bar(stat = &quot;summary&quot;, fun = mean, position = &quot;dodge&quot;) + 
    geom_errorbar(stat = &quot;summary&quot;, position = position_dodge(0.9), 
        width = 0.5) + scale_fill_manual(&quot;legend&quot;, values = c(ACERRU = &quot;seagreen1&quot;, 
    QUERRU = &quot;seagreen&quot;)) + theme(panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), legend.position = c(0.9, 
        0.85)) + ggtitle(&quot;Mean Area for each Species per Plot&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>The grouped bar plot above shows the mean ionization area and variance for each species in each plot. From this data, you can see that there is less area of compounds in QUERRU than ACERRU across each plot. It shows that the mean area for both ACERRU and QUERRU is largest in the SERC (SR) plot, and smallest in the SCBI (SB) plot for QUERRU and in the Michigan (UM) plot for ACERRU. The graph shows that in the Michigan plot the species are not much different in terms of area. Intraspecifically, all of the mean areas for QUERRU across each plot are very similar in terms of variance and mean area. For ACERRU, the mean area is very similar amongst SB, SR, and Tyson (TR), but a lot lower in UM. Some of these differences could be atttributed to outliers that exist in the data, but this is a great visualization to lead us in how we should continue to analyze the data. </em></p>
<p><em>Boxplot</em></p>
<pre class="r"><code>AQ_Joined %&gt;% ggplot(aes(x = Plot, y = Molecular.Weight, color = Plot, 
    fill = Species)) + geom_boxplot() + scale_y_continuous(breaks = seq(0, 
    900, 50)) + scale_fill_manual(&quot;legend&quot;, values = c(ACERRU = &quot;seagreen1&quot;, 
    QUERRU = &quot;seagreen&quot;)) + scale_color_manual(&quot;legend&quot;, values = c(SB = &quot;orchid&quot;, 
    SR = &quot;mediumpurple&quot;, TR = &quot;gray72&quot;, UM = &quot;plum&quot;)) + labs(y = &quot;Molecular Weight&quot;, 
    title = &quot;Molecular Weight of Compounds for each Species in each Plot&quot;) + 
    theme_minimal()</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" /> <em>The plot above shows the molecular weight for each Species in each plot. The fill of the boxplots corresponds to the type of species being represented and the outline of the boxplot shows the plot that the species is in, as show in the two legends. From this visualization, it shows that the median molecular weight in each species and plot are almost the same or the same. The variance differs across Species, but not across plots within species. In terms of the molecular weight spread, it appears that the majority of the compounds are below 300 grams in weight, but that there are also bunches of compounds that weigh more. In the future, this mass amount of compounds may need to be filtered out through chromatogram noise thresholds as they may be noise in the data. It is important to view graphs like these so that you can know where most of your data lies and the type of filtering that must be down downstream. </em></p>
</div>
<div id="dimensionality-reduction" class="section level2">
<h2>5. DIMENSIONALITY REDUCTION</h2>
<pre class="r"><code># this line was giving the cluster code troubles and the name
# needed to be changed to a better format
AQ_Joined &lt;- AQ_Joined %&gt;% mutate(Name = str_replace(Name, &quot;3&lt;df&gt;-Androstanediol&quot;, 
    &quot;Androstanediol&quot;))


# Created a kmeans for 3 clusters as a prediction:
library(cluster)
clust_dat &lt;- AQ_Joined %&gt;% ungroup() %&gt;% dplyr::select_if(is.numeric)
clust_dat</code></pre>
<pre><code>## # A tibble: 33,848 x 4
##    Molecular.Weight RT..min.        Area Full.Match
##               &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;      &lt;int&gt;
##  1             386.     12.0 1667380538.          4
##  2             386.     12.0 1780540427.          4
##  3             386.     12.0 1341439436.          4
##  4             386.     12.0 1520274599.          4
##  5             386.     12.0 1146859589.          4
##  6             386.     12.0 1386355736.          4
##  7             386.     12.0 1726770446.          4
##  8             386.     12.0 1104149542.          4
##  9             386.     12.0 1571800011.          4
## 10             386.     12.0 1484915548.          4
## # … with 33,838 more rows</code></pre>
<pre class="r"><code>kmeansAQ &lt;- clust_dat %&gt;% scale %&gt;% kmeans(3)
kmeansAQ$size</code></pre>
<pre><code>## [1] 17809  3112 12927</code></pre>
<pre class="r"><code>kmeansAQ$centers</code></pre>
<pre><code>##   Molecular.Weight   RT..min.        Area Full.Match
## 1       -0.5525027 -0.6614239 -0.10325084 -0.2480848
## 2       -0.2966592 -0.3616690  0.37557205  2.6002555
## 3        0.8325771  0.9982836  0.05183059 -0.2842000</code></pre>
<pre class="r"><code>kmeansAQ$betweenss</code></pre>
<pre><code>## [1] 59596.86</code></pre>
<pre class="r"><code># visualizing what 3 clusters looks like:
kmeansclustAQ &lt;- clust_dat %&gt;% mutate(cluster = as.factor(kmeansAQ$cluster))
kmeansclustAQ %&gt;% ggplot(aes(Molecular.Weight, RT..min., color = cluster)) + 
    geom_point()</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># deciding on number of clusters through a silhouette width:
sil_width &lt;- vector()
for (i in 2:10) {
    kms &lt;- kmeans(clust_dat, centers = i)
    sil &lt;- silhouette(kms$cluster, dist(clust_dat))
    sil_width[i] &lt;- mean(sil[, 3])
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># put 2 cluster kmeans into a cluster assignment and plot to
# make sure that the clusters are split
finalAQ &lt;- AQ_Joined %&gt;% ungroup %&gt;% select(is.numeric) %&gt;% scale %&gt;% 
    as.data.frame
finalAQ_kmeans &lt;- finalAQ %&gt;% kmeans(2)
kmeansclust2 &lt;- finalAQ %&gt;% mutate(cluster = as.factor(finalAQ_kmeans$cluster))
kmeansclust2 %&gt;% ggplot(aes(RT..min., Molecular.Weight, color = cluster)) + 
    geom_point()  #clusters are relatively split this way with 2 kmeans </code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-18-2.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>In order to better understand how my data is clustered, I used the kmeans method in order to observe how my numeric variables were associated with one another. I first created a scaled vector that predicted 3 clusters named <code>kmeansAQ</code>. Once I graphed this, I realized that I should go back and see how many clusters I should using a silhouette graph as the clusters were not very clear. The higher values in the silhouette graph for silhouette width are 2 and 3, both being above 0.95. I decided to go with 2 as it seems to be the best value predicted from this tool. I finalized a cluster assignment of kmeans=2 for this data, and found that the clusters were more spread apart this way than with kmeans=3.</em></p>
<pre class="r"><code># visualizing the clusters:
library(GGally)
ggpairs(kmeansclust2, columns = 1:4, aes(color = cluster))</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-19-1.png" width="672" style="display: block; margin: auto;" /> <em>The data redundancy is more clear after analyzing this pairwise distribution of our clusters across the 4 numeric variables I included in this analysis. The clusters of data are not super clear in this dataset as the samples are from the same two species from the same four forest plots. It is expected that their chemical composition should be mostly the same. One important trend that you can see from this data is that retention time and molecular weight are strongly correlated as retention time is calculated from molecular weight. On the other hand, Area is not strongly correlated to retention time or molecular weight. Additionally, retention time, molecular weight, and area (measurement variables) do not have a strong correlation with the full match variable, which makes sense as it is not produced by the mass spectrometry machine itself, but the program that analyzes this data. This visualization and clustering method makes it clear that when moving forward we will need to consider area and either retention time or molecular weight when comapring this data against other species and itself.</em></p>
<p><em>In conclusion, this project investigated the variables represented in mass spectrometry data from two species, Acer rubra and Quercus alba, from four different North American forest plots. The visualizations and summary statistics produce from this analysis will be used for further investigation in the intra and interspecific chemical similarities and differences amongst these two species. The generated metabolomic data is from the Sedio lab at the University of Texas at Austin and was processed on Compound Discover before being manipulated and analyzed in R studio. </em></p>
</div>
</div>
