---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Lauren Hart"
date: '11/08/2020'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<pre class="r"><code>#classification diagnostics function:
class_diag&lt;-function(probs,truth){
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE){
    truth&lt;-as.numeric(truth)-1}
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}</code></pre>
<div id="introdcution" class="section level1">
<h1>0. Introdcution</h1>
<pre class="r"><code>#loading the dataset and minor adjustments: 
library(tidyverse)
forestfires &lt;- read_csv(&quot;forestfires.csv&quot;) %&gt;% as.data.frame
forestdata &lt;- forestfires %&gt;% mutate(logarea = log1p(area))
#mean centering variables: 
forestdata &lt;- forestdata %&gt;% mutate(meantemp = temp- mean(temp)) %&gt;% mutate(meanRH = RH- mean(RH)) %&gt;% mutate(meanwind = wind- mean(wind)) %&gt;% mutate(meanlogarea = logarea- mean(logarea)) %&gt;% mutate(meanDC = DC - mean(DC)) %&gt;% mutate(meanISI = ISI - mean(ISI)) %&gt;% mutate(meanrain = rain - mean(rain))</code></pre>
<p><em>This dataset was generated by Paulo Cortez and Aniíbal Morais from the University of Minho in Portugal. The dataset has information about 517 indepdendent forest fires from January 2000 to Decemner 2003 and the relevant weather patterns and indices from Montesinho natural park in the Northeast region of Portugal. The dataset includes basic weather pattern variables such as outside temperature (<code>temp</code>, Celsius), outside relative humidity (<code>RH</code>, %), outside wind speed (<code>wind</code>, km/hr), and outside rain (<code>rain</code>, mm/mm^2). There are identifying variables for the x and y-axis coordinate of the fire (<code>X</code>, <code>Y</code>) and the month and day of the year that the fire took place (<code>month</code>, <code>day</code>). There are also indices that explain the conditions prior to a fire as well as the behavior of the fire. The drought code (<code>DC</code>, represents drying deep into the soil) and initial spread index (<code>ISI</code>, estimates a spread potential by integrating fuel moisture for fine dead fuels and windspeed) are the two indeces I will use along with the other variables listed above to predict forest fire area (<code>area</code>, hectares.). The area variable had to be log transformed due to its' tendency to go towards zero. The paper that this data comes from and explains how it was created, merged, and analyzed for further studies can be found at this link: <a href="http://piano.dsi.uminho.pt/~pcortez/fires.pdf" class="uri">http://piano.dsi.uminho.pt/~pcortez/fires.pdf</a>.</em></p>
</div>
<div id="manova-test" class="section level1">
<h1>1. MANOVA test</h1>
<pre class="r"><code>#checking MANOVA assumptions: 
#multivariate normality: 
forestdata %&gt;% group_by(day) %&gt;% count()</code></pre>
<pre><code>## # A tibble: 7 x 2
## # Groups:   day [7]
##   day       n
##   &lt;chr&gt; &lt;int&gt;
## 1 fri      85
## 2 mon      74
## 3 sat      84
## 4 sun      95
## 5 thu      61
## 6 tue      64
## 7 wed      54</code></pre>
<pre class="r"><code>#homogeneity of within-groupcovariance matrices: 
covmats &lt;- forestdata %&gt;% group_by(day) %&gt;% do(covs=cov(.[5:11]))
for(i in 1:7){print(as.character(covmats$day[i])); print(covmats$covs[[i]])}</code></pre>
<pre><code>## [1] &quot;fri&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 16.183454 93.88836 387.5616 9.7477563 8.860746
-16.682661 -1.4729482
## DMC 93.888357 4698.57076 13442.3202 54.3770952
139.468167 169.026905 -28.0495238
## DC 387.561632 13442.32024 76365.2250 360.5450210
604.359314 818.177241 -145.5359384
## ISI 9.747756 54.37710 360.5450 13.1341653 6.090538
-6.426975 0.2691737
## temp 8.860746 139.46817 604.3593 6.0905378 25.930622
-45.172633 -2.7857843
## RH -16.682661 169.02690 818.1772 -6.4269748 -45.172633
269.513165 4.0265406
## wind -1.472948 -28.04952 -145.5359 0.2691737 -2.785784
4.026541 3.4515126
## [1] &quot;mon&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 17.184680 115.64539 382.6630 10.328589 10.662817
-1.752314 -2.670289
## DMC 115.645391 2898.47933 9604.4333 103.140574
205.862977 108.138708 -46.336105
## DC 382.662991 9604.43331 71341.5771 346.194287
877.610059 240.226971 -162.985054
## ISI 10.328589 103.14057 346.1943 12.833750 12.831159
-2.856831 -1.855772
## temp 10.662817 205.86298 877.6101 12.831159 40.539519
-39.670085 -5.924846
## RH -1.752314 108.13871 240.2270 -2.856831 -39.670085
267.843206 -2.374713
## wind -2.670289 -46.33611 -162.9851 -1.855772 -5.924846
-2.374713 3.340740
## [1] &quot;sat&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 35.7880709 157.392701 756.3569 13.574726 14.698252
-29.676621 0.8521185
## DMC 157.3927008 4840.173544 12978.0754 82.238685
160.199026 186.168474 8.4134438
## DC 756.3569162 12978.075402 67852.6024 394.097025
741.274025 -269.305737 -27.4788956
## ISI 13.5747260 82.238685 394.0970 15.849000 5.676353
-5.311675 1.3420382
## temp 14.6982516 160.199026 741.2740 5.676353 28.895782
-48.681440 -1.5008333
## RH -29.6766208 186.168474 -269.3057 -5.311675 -48.681440
264.026965 1.4050201
## wind 0.8521185 8.413444 -27.4789 1.342038 -1.500833
1.405020 2.8260743
## [1] &quot;sun&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 80.281471 205.09355 413.37971 19.678019 19.0179138
-62.5466741 1.7587312
## DMC 205.093546 4374.58759 9900.24983 54.452366
166.4747044 -25.2311198 25.6173247
## DC 413.379712 9900.24983 56122.22175 -122.296985
766.3659115 -761.1630011 11.4569810
## ISI 19.678019 54.45237 -122.29699 36.308526 6.8299866
-17.8981747 2.3474558
## temp 19.017914 166.47470 766.36591 6.829987 35.2627167
-62.5362150 0.1095364
## RH -62.546674 -25.23112 -761.16300 -17.898175
-62.5362150 302.2436730 -0.3960694
## wind 1.758731 25.61732 11.45698 2.347456 0.1095364
-0.3960694 3.7503091
## [1] &quot;thu&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 9.2746339 90.219404 362.2312 7.4578634 14.550369
-27.948087 -0.4689727
## DMC 90.2194044 5033.644568 11944.7489 35.3394071
195.790451 3.965301 -26.4304481
## DC 362.2312350 11944.748880 57037.5620 158.3372568
774.451273 -1017.152596 -105.8532514
## ISI 7.4578634 35.339407 158.3373 12.6674863 12.611787
-24.128142 0.9993361
## temp 14.5503689 195.790451 774.4513 12.6117869 37.889475
-57.632350 -1.4688907
## RH -27.9480874 3.965301 -1017.1526 -24.1281421
-57.632350 199.127322 1.1956284
## wind -0.4689727 -26.430448 -105.8533 0.9993361 -1.468891
1.195628 2.7026995
## [1] &quot;tue&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 21.5357837 170.08817 572.0466 19.242034 15.208199
-7.866716 -0.2854464
## DMC 170.0881746 2758.79524 8106.3386 170.097222
177.174960 95.278968 -18.9464286
## DC 572.0465675 8106.33857 47335.5152 484.573194
564.870486 122.639980 -128.2812897
## ISI 19.2420337 170.09722 484.5732 27.689514 13.118686
5.181200 1.1348512
## temp 15.2081994 177.17496 564.8705 13.118686 29.278609
-32.977455 -3.3849157
## RH -7.8667163 95.27897 122.6400 5.181200 -32.977455
249.747768 4.6652282
## wind -0.2854464 -18.94643 -128.2813 1.134851 -3.384916
4.665228 2.8344345
## [1] &quot;wed&quot;
## FFMC DMC DC ISI temp RH wind
## FFMC 6.0707233 57.99943 137.8802 8.3846855 9.837893
-15.412579 -0.2223166
## DMC 57.9994340 3473.53660 8488.5528 130.3711321
148.590377 66.571698 -15.9559119
## DC 137.8802201 8488.55283 48937.3968 191.3817296
574.347767 -78.032704 -140.4190042
## ISI 8.3846855 130.37113 191.3817 18.6722327 16.759591
-15.869182 0.4898847
## temp 9.8378931 148.59038 574.3478 16.7595912 35.241289
-52.808805 -2.1850839
## RH -15.4125786 66.57170 -78.0327 -15.8691824 -52.808805
221.798742 3.1457023
## wind -0.2223166 -15.95591 -140.4190 0.4898847 -2.185084
3.145702 2.8773760</code></pre>
<pre class="r"><code>#MANOVA test: 
manforest &lt;- manova(cbind(meanlogarea, meanDC, meanISI, meantemp, meanRH, meanwind, meanrain) ~ day, data = forestdata)
summary(manforest)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## day 6 0.1644 2.0486 42 3054 8.66e-05 ***
## Residuals 510
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>#univariate ANOVA: 
summary.aov(manforest)</code></pre>
<pre><code>## Response meanlogarea :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 4.22 0.7031 0.3568 0.9059
## Residuals 510 1004.88 1.9704
##
## Response meanDC :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 225065 37511 0.6068 0.725
## Residuals 510 31527942 61819
##
## Response meanISI :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 464.3 77.386 3.8457 0.0009205 ***
## Residuals 510 10262.7 20.123
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response meantemp :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 561.6 93.601 2.8353 0.01005 *
## Residuals 510 16836.3 33.012
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response meanRH :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 5436 906.03 3.5018 0.002103 **
## Residuals 510 131954 258.73
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response meanwind :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 42.24 7.0405 2.2245 0.03957 *
## Residuals 510 1614.13 3.1650
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response meanrain :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## day 6 0.901 0.150209 1.7294 0.1121
## Residuals 510 44.296 0.086855</code></pre>
<pre class="r"><code>#post-hoc tests: 
pairwise.t.test(forestdata$RH, forestdata$day, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  forestdata$RH and forestdata$day 
## 
##     fri     mon     sat     sun     thu     tue    
## mon 0.43532 -       -       -       -       -      
## sat 0.18912 0.62412 -       -       -       -      
## sun 0.33665 0.08483 0.02132 -       -       -      
## thu 0.00377 0.03567 0.08963 0.00013 -       -      
## tue 0.26237 0.71850 0.92032 0.04225 0.09135 -      
## wed 0.01971 0.11453 0.24096 0.00131 0.66364 0.23147
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(forestdata$ISI, forestdata$day, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  forestdata$ISI and forestdata$day 
## 
##     fri     mon     sat     sun     thu     tue    
## mon 0.00172 -       -       -       -       -      
## sat 0.20360 0.05623 -       -       -       -      
## sun 0.44614 0.01285 0.58420 -       -       -      
## thu 0.31407 0.05556 0.87371 0.73639 -       -      
## tue 0.63566 0.00074 0.09890 0.23496 0.16712 -      
## wed 0.12699 2.2e-05 0.00835 0.02626 0.02027 0.31059
## 
## P value adjustment method: none</code></pre>
<p><em>The null hypothesis of this MANOVA is that all of the response variables (DC, ISI, temp, RH, rain, and area) do not show a mean difference across days of the week. The alternate hypothesis is that at least one of the response variables (area, DC, ISI, temp, RH, rain, and area) does show a mean difference across days of the week. For MANOVA assumptions: the data has independent observations and it includes all of the forest fires between January 2000 to December 2003. Multivariate normality is met because each day of the week has more than 25 observations. The data fails the homogeneity of covariances as the covariances are extremely scattered. The data is not likely to pass the linearity assumption, multicollinearity, or extreme outliers assumptions as some of the variables are going to be more correlated than others due to them being related to weather patterns, and some may have outliers due to adverse weather conditions seen when forest fires begin. After running the MANOVA test and getting a significant p-value (p = 8.66e-05, df = 42, F = 2.0486), we can reject the null hypothesis and conclude that for at least one response variable, at least one day mean is different. Due to the significant result, 6 one-way ANOVA's were ran to analyze which response variable means were actually different. With the alpha value adjusted using the bonferroni correction ,the new alpha value is 0.0083 (7 tests ran total). Only RH and ISI are significant after this correction and have significantly different means for each day. Post-hoc tests were ran for these two variables. The adjusted alpha value after the MANOVA, univariate ANOVA's, and posthoc tests (9 tests total) would be 0.0055. For RH, the days that the mean RH significnatly differs are Sunday from Wednesday and Thursday and Thursday from Friday. For ISI, the days that the mean ISI significantly differs are Monday from Tuesday, Wednesday, and Friday, as well as Saturday from Wednesday. After 9 tests were ran in total, the probability of making a type I error is 0.3698 (36.98% chance).</em></p>
</div>
<div id="randomization-test" class="section level1">
<h1>2. Randomization test</h1>
<pre class="r"><code>#observed F-statistic: 
forestdata &lt;- forestdata %&gt;% mutate(as.factor(day))
forestaov &lt;- aov(meanlogarea ~ day, data = forestdata)
summary.aov(forestaov)</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## day           6    4.2  0.7031   0.357  0.906
## Residuals   510 1004.9  1.9704</code></pre>
<pre class="r"><code>#generating random distribution: 
obs_F&lt;-0.357 
Fs&lt;-replicate(5000,{ 
new&lt;-forestdata%&gt;%mutate(logarea=sample(logarea)) 
SSW&lt;- new%&gt;%group_by(day)%&gt;%summarize(SSW=sum((logarea-mean(logarea))^2))%&gt;%
summarize(sum(SSW))%&gt;%pull
SSB&lt;- new%&gt;%mutate(mean=mean(logarea))%&gt;%group_by(day)%&gt;%mutate(groupmean=mean(logarea))%&gt;%
summarize(SSB=sum((mean-groupmean)^2))%&gt;%summarize(sum(SSB))%&gt;%pull
(SSB/6)/(SSW/511) 
})
#p-value: 
mean(Fs&gt;obs_F)</code></pre>
<pre><code>## [1] 0.9088</code></pre>
<pre class="r"><code>#distribution of null distribution and test statistic: 
hist(Fs, prob = T); abline(v = obs_F, col = &quot;red&quot;, add = T)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /> <em>For the randomization test, I calculated a randomized one-way ANOVA to see if mean logarea of the forest fires was equal across each day of the week. The null hypothesis is that mean logarea is the same across each day of the week. The alternative hypothesis is that mean logarea is different across at least one of the days of the week. The observed F statistic is 0.357 (p = 0.906, df=6). The simulated F statistic is 30.57223, much larger than the observed F statistic. The p-value is 0.9016, meaning that there is not a statistically significant difference between mean logarea and the day of the week that the forest fire occured on. As you can see from the distribution of the null distribution from the randomization test with the observed F statistic as the red line, only a small amount of the data sits below the actual F statistic, and the majority is greater than the actual F statistic, meaning the days do not differ by much in their logarea for the forest fire.</em></p>
</div>
<div id="linear-regresion-model" class="section level1">
<h1>3. Linear regresion model</h1>
<pre class="r"><code>#linear regression model:
fitforest &lt;- lm(meanlogarea ~ meanRH * meantemp * meanwind, data = forestdata)
summary(fitforest)</code></pre>
<pre><code>##
## Call:
## lm(formula = meanlogarea ~ meanRH * meantemp * meanwind,
data = forestdata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -1.6447 -1.1032 -0.6059 0.8723 5.7778
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -3.814e-02 7.045e-02 -0.541 0.588
## meanRH 4.197e-04 5.281e-03 0.079 0.937
## meantemp 2.217e-02 1.403e-02 1.581 0.115
## meanwind 3.857e-02 3.849e-02 1.002 0.317
## meanRH:meantemp -1.291e-04 6.128e-04 -0.211 0.833
## meanRH:meanwind -8.964e-04 2.633e-03 -0.340 0.734
## meantemp:meanwind -1.430e-02 6.177e-03 -2.315 0.021 *
## meanRH:meantemp:meanwind -8.254e-06 3.091e-04 -0.027
0.979
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 1.393 on 509 degrees of freedom
## Multiple R-squared: 0.02117, Adjusted R-squared:
0.007705
## F-statistic: 1.572 on 7 and 509 DF, p-value: 0.1411</code></pre>
<pre class="r"><code>#checking linear regression assumptions: 
   #normality 
resids &lt;- fitforest$residuals
shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.84707, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>   #linearity 
fitvals &lt;- fitforest$fitted.values
ggplot() + geom_point(aes(fitvals, resids)) + geom_hline(yintercept = 0, color = &quot;red&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>   #homoskedasticity 
library(sandwich)
library(lmtest)
bptest(fitforest)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fitforest
## BP = 7.8128, df = 7, p-value = 0.3494</code></pre>
<pre class="r"><code>#plot of linear regression: 
library(interactions)
interact_plot(fitforest, pred = meantemp, modx = meanwind, plot.points = TRUE)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#recomputed linear regression with robust standard errors: 
coeftest(fitforest, vcov=vcovHC(fitforest))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -3.8143e-02 6.9799e-02 -0.5465 0.58498
## meanRH 4.1966e-04 5.3909e-03 0.0778 0.93798
## meantemp 2.2173e-02 1.3941e-02 1.5905 0.11233
## meanwind 3.8575e-02 3.6457e-02 1.0581 0.29051
## meanRH:meantemp -1.2907e-04 6.1399e-04 -0.2102 0.83359
## meanRH:meanwind -8.9638e-04 2.6362e-03 -0.3400 0.73398
## meantemp:meanwind -1.4297e-02 5.6016e-03 -2.5523 0.01099
*
## meanRH:meantemp:meanwind -8.2539e-06 2.7977e-04 -0.0295
0.97648
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>For this linear regression, I am investigating how wind, temperature, and relative humidity predict the logarea of a forest fire in this dataset. The null hypothesis is that the slope is 0 between each predictor (wind, temp, RH) and the response variable (logarea). The alternative hypothesis is that the slope is not 0 between each predictor (wind, temp, RH) and the response variable (logarea). For assumptions, normality was assesed with the Shapiro-Wilk test. The p-vaue for the test was 2.2e-16, meaning we reject the null and assume that the true distribution is not normal, failing to meet the normality assumption. For the test of linearity, a scatterplot was made for the fitted values vs. the residuals and does not represent full linearity for the model, so we also reject that assumption. For the homoskedasticity assumption, I ran the Breusch-Pagan test. The p-value for the BP test is 0.3494, being above the alpha value of 0.05, and accepting the null that the distribution of the model meets the assumptions of homoskedasticity.</em> <em>Interpreting the coefficients of the model-main effects: -3.814e-02 hectares is the predicted mean logarea of forest burned when wind, temperature, and relative humidity are average. Controlling for temperature and wind, mean logarea of the forest burned increases 4.1966e-04 hectares for every one percent increase in relative humidity. Controlling for relative humidity and wind, mean logarea of the forest burned increases 2.2173e-02 hectares for every one degree celsius increase in temperature. Controlling for relative humidity and temperature, mean logarea of the forest burned increases 3.8575e-02 hectares for every one kilometer per hour increase in wind.</em><br />
<em>Interpreting the coeffecients of the model-interactions: Controlling for relative humidity, average temperature and wind have a significant interaction effect on log area of a forest fire, being a -1.430e-02 hectare decrease of logarea of a forest fire. When controlling for wind, there is a -1.291e-04 hectare decrease in logarea of a forest fire due to the interaction of average relative humidity and temperature. Controlling for temperature, there is a -8.964e-04 hectare decrease in logarea of a forest fire due to the interaction of relative humidity and wind. The interaction between average wind, temperature, and relative humidity results in a -8.254e-06 hectare decrease in logarea of a forest fire. For the entire model, the adjusted R^2 is 0.007705. This means that only 0.7705% of the variance in mean logarea of forest burned in hectares can be explained by mean relative humidity, mean temperature, and mean wind. As you can see from the interaction plot, the slope of mean log area of forest burned on mean temperature changes as a function of mean wind. Their interaction shows to be at 0 and 0 for both mean temperature and mean log area (where the lines intersect).</em> <em>When robsust standard errors were done for this model, the results that were significant stayed significant with slight changes to the p values. Controlling relative humidity before standard robust errors, the p-value for the interaction between temperature and wind on logarea of a forest fire was 0.021 and with robust standard errors the result stayed significant with a p-value of 0.01099. The intercept stayed significant as well with the same p-value being 2e-16.The estimates for the rest of the coefficients stayed relatively constant after this transformation of the standard errors.</em></p>
</div>
<div id="bootstrapped-standard-errors-linear-regression-model" class="section level1">
<h1>4. Bootstrapped standard errors linear regression model</h1>
<pre class="r"><code>#bootstrapped standard errors: 
samp_distn&lt;-replicate(5000, {
boot_dat&lt;-boot_dat&lt;-forestdata[sample(nrow(forestdata),replace=TRUE),]
fitdataforest &lt;- lm(meanlogarea ~ meanRH * meantemp * meanwind, data = boot_dat)
coef(fitdataforest)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) meanRH meantemp meanwind meanRH:meantemp
meanRH:meanwind meantemp:meanwind
## 1 0.07006887 0.005290143 0.01388407 0.0367151
0.0006172225 0.002652134 0.005826377
## meanRH:meantemp:meanwind
## 1 0.0002904905</code></pre>
<pre class="r"><code>samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%gather%&gt;%group_by(key)%&gt;%
summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 8 x 3
##   key                          lower     upper
##   &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              -0.176     0.0998  
## 2 meanRH                   -0.00989   0.0108  
## 3 meanRH:meantemp          -0.00140   0.00106 
## 4 meanRH:meantemp:meanwind -0.000581  0.000557
## 5 meanRH:meanwind          -0.00606   0.00448 
## 6 meantemp                 -0.00447   0.0494  
## 7 meantemp:meanwind        -0.0250   -0.00193 
## 8 meanwind                 -0.0347    0.108</code></pre>
<p><em>I calculated bootstrapped standard errors for the linear regression that is predicting mean logarea of a forest fire from average wind, temperature, and relative humidity. Comparing the bootstrapped standard errors to the original linear regression model, the standard errors are not much different, where they vary by hundreths of a decimal place. The bootstrapped standard errors in comparison to the robust standard errors are almost exactly the same, varying by a tiny amount that could be due to chance. All of the confidence intervals for main effects and interactions contain 0, the null value for the test, except for the interaction between mean temperature and mean wind. This result makes sense as this was the significant interaction in the regression ran above. No other effects became significant with the bootstrapped standard errors.</em></p>
</div>
<div id="logistic-regression-predicting-binary-variable" class="section level1">
<h1>5. Logistic regression predicting binary variable</h1>
<pre class="r"><code>#making dummy variable: 1= weekend (Friday, Saturday, Sunday), 0 = weekday (Monday, Tuesday, Wednesday, Thursday)
forestdata &lt;- forestdata %&gt;% mutate(day_b = ifelse(forestdata$day == c(&quot;fri&quot;, &quot;sat&quot;, &quot;sun&quot;), 1, 0)) 
#model
forestdatafit &lt;- glm(day_b ~ meanlogarea + meanDC, data = forestdata, family=binomial)
summary(forestdatafit)</code></pre>
<pre><code>##
## Call:
## glm(formula = day_b ~ meanlogarea + meanDC, family =
binomial,
## data = forestdata)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -0.6625 -0.6201 -0.5996 -0.5519 2.1235
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.6176442 0.1187264 -13.625 &lt;2e-16 ***
## meanlogarea -0.0846818 0.0893893 -0.947 0.343
## meanDC -0.0002206 0.0004676 -0.472 0.637
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 465.34 on 516 degrees of freedom
## Residual deviance: 464.13 on 514 degrees of freedom
## AIC: 470.13
##
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp(coef(forestdatafit))</code></pre>
<pre><code>## (Intercept) meanlogarea      meanDC 
##   0.1983655   0.9188046   0.9997794</code></pre>
<pre class="r"><code>#confusion matrix
probs &lt;- predict(forestdatafit, type = &quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=forestdata$day_b)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   431  86 517
##     Sum 431  86 517</code></pre>
<pre class="r"><code>truth &lt;- forestdata$day_b
#classification diagnostics: 
class_diag(probs, truth)</code></pre>
<pre><code>##         acc sens spec ppv  f1       auc
## 1 0.8336557    0    1 NaN NaN 0.5356796</code></pre>
<pre class="r"><code>#ROC curve
library(plotROC) 
ROCplot&lt;-ggplot(forestdata)+geom_roc(aes(d=day_b,m=probs), n.cuts=0) 
ROCplot</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5356796</code></pre>
<pre class="r"><code>#plot of log-odds
forestdata$logit&lt;-predict(forestdatafit, type = &quot;link&quot;) 
forestdata %&gt;% ggplot()+geom_density(aes(logit,color = day_b, fill=day_b), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=day_b, fill = day_b))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-2.png" width="768" style="display: block; margin: auto;" /> <em>I coded the day variable into weekend and weekdays, where 1 is equal to Friday, Saturday, and Sunday, and 0 is equal to Monday, Tuesday, Wednesday, and Thursday. I ran a logistic regression using mean log area and drought code to predict weekend or weekday. The only significant coefficient is for the intercept, having a p-value of 2e-16, and indicating that when logarea forest fire and drought code are both average, it is a 19.8% chance that it is a weekend (the reference group) compared to being a weekday. Controlling for mean drought code, for every 1 unit increase in mean log area hectares of forest burned, the odds of it being a weekend are 0.9188 times the odds of it being a weekday. Controlling for mean log area of forest burned in hectares, the odds of it being a weekend are 0.9997794 times the odds of it being a weekday. When a confusion matrix was made for this regression, you can see that the accuracy is 0.8337, the sensitivty is 0, the specificity is 1, the precision is 0 (0/86), and the AUC is 0.5356796. The AUC shows that the model is bad at predicting. The sensitivity is 0 because 0 no positive values were predicted correctly, and the specificity is 1 because all values were being predicted to not be a weekend. When the ROC plot was made, it is almost a staight line (as bad as it could really get almost). This indicates the model is really not predicting well at all. The log-odds plot shows an odds density for only the negative values (being a weekday) as the true positive rate was 0, and the true negative rate was 1. This is just another example of how poorly the model is at predicting true positives.</em></p>
</div>
<div id="logistic-regression-predciting-binary-variable-from-other-variables" class="section level1">
<h1>6. Logistic regression predciting binary variable from other variables</h1>
<pre class="r"><code>#logistic regression model:
newdata &lt;- forestdata %&gt;% select(c(X, Y, meanrain, meanISI, meantemp, meanRH, meanwind, meanlogarea, meanDC, day_b))
fit2 &lt;- glm(day_b ~ (.)^2 , data= newdata, family = binomial)
summary(fit2)</code></pre>
<pre><code>##
## Call:
## glm(formula = day_b ~ (.)^2, family = binomial, data =
newdata)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -1.5891 -0.6370 -0.4812 -0.2707 2.3843
##
## Coefficients: (1 not defined because of singularities)
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -8.175e+00 1.415e+03 -0.006 0.99539
## X 7.308e-01 7.753e+01 0.009 0.99248
## Y 9.354e-02 1.541e+02 0.001 0.99952
## meanrain -1.997e+02 6.532e+04 -0.003 0.99756
## meanISI -1.399e-01 5.512e+01 -0.003 0.99798
## meantemp 5.151e-01 1.218e+02 0.004 0.99663
## meanRH 2.088e-01 4.115e+01 0.005 0.99595
## meanwind -1.153e+00 9.964e+01 -0.012 0.99077
## meanlogarea -7.836e-01 2.330e+02 -0.003 0.99732
## meanDC 3.404e-04 3.463e-03 0.098 0.92169
## X:Y -7.586e-02 4.413e-02 -1.719 0.08560 .
## X:meanrain 1.711e+01 3.579e+03 0.005 0.99618
## X:meanISI 1.879e-02 1.846e-02 1.018 0.30876
## X:meantemp -1.495e-02 2.066e-02 -0.723 0.46937
## X:meanRH -3.617e-03 6.031e-03 -0.600 0.54869
## X:meanwind -5.212e-02 4.268e-02 -1.221 0.22199
## X:meanlogarea 3.682e-03 4.899e-02 0.075 0.94009
## X:meanDC -1.924e-04 3.840e-04 -0.501 0.61632
## Y:meanrain -1.674e+01 7.113e+03 -0.002 0.99812
## Y:meanISI -6.646e-02 4.082e-02 -1.628 0.10347
## Y:meantemp 2.430e-02 4.079e-02 0.596 0.55145
## Y:meanRH 2.466e-03 1.333e-02 0.185 0.85320
## Y:meanwind 1.871e-01 9.060e-02 2.066 0.03887 *
## Y:meanlogarea 4.973e-04 9.233e-02 0.005 0.99570
## Y:meanDC 2.365e-04 7.422e-04 0.319 0.74994
## meanrain:meanISI -1.604e+01 2.544e+03 -0.006 0.99497
## meanrain:meantemp 1.992e+01 5.624e+03 0.004 0.99717
## meanrain:meanRH 8.166e+00 1.899e+03 0.004 0.99657
## meanrain:meanwind -3.406e+01 4.600e+03 -0.007 0.99409
## meanrain:meanlogarea -3.244e+01 1.076e+04 -0.003 0.99759
## meanrain:meanDC NA NA NA NA
## meanISI:meantemp -4.225e-02 1.076e-02 -3.927 8.6e-05 ***
## meanISI:meanRH -6.071e-03 2.917e-03 -2.081 0.03745 *
## meanISI:meanwind -2.305e-02 2.281e-02 -1.010 0.31235
## meanISI:meanlogarea 1.264e-02 2.995e-02 0.422 0.67293
## meanISI:meanDC 6.233e-04 2.320e-04 2.687 0.00721 **
## meantemp:meanRH -8.305e-04 1.561e-03 -0.532 0.59463
## meantemp:meanwind 9.479e-03 2.285e-02 0.415 0.67823
## meantemp:meanlogarea -5.024e-02 2.997e-02 -1.677 0.09362
.
## meantemp:meanDC 3.118e-04 1.688e-04 1.847 0.06481 .
## meanRH:meanwind -6.597e-03 6.575e-03 -1.003 0.31569
## meanRH:meanlogarea -1.050e-02 8.736e-03 -1.202 0.22942
## meanRH:meanDC 8.419e-05 4.738e-05 1.777 0.07558 .
## meanwind:meanlogarea -1.005e-01 6.776e-02 -1.483 0.13816
## meanwind:meanDC -2.115e-04 4.328e-04 -0.489 0.62497
## meanlogarea:meanDC 2.037e-04 5.582e-04 0.365 0.71512
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 465.34 on 516 degrees of freedom
## Residual deviance: 411.90 on 472 degrees of freedom
## AIC: 501.9
##
## Number of Fisher Scoring iterations: 15</code></pre>
<pre class="r"><code>probsforest &lt;- predict(fit2, type = &quot;response&quot;)
truthforest &lt;- newdata$day_b
#in sample classification diagnostics: 
class_diag(probsforest, truthforest)</code></pre>
<pre><code>##         acc      sens      spec       ppv   f1       auc
## 1 0.8413926 0.1046512 0.9883991 0.6428571 0.18 0.7200939</code></pre>
<pre class="r"><code>#10-fold cross validation and out of sample classification diagnostics: 
set.seed(1234)
k=10 

data&lt;-newdata[sample(nrow(newdata)),] 
folds&lt;-cut(seq(1:nrow(newdata)),breaks=k,labels=F) 

diags&lt;-NULL
for(i in 1:k){
  
  train&lt;-newdata[folds!=i,] 
  test&lt;-newdata[folds==i,]
  truth&lt;-test$day_b
  
  
  fit&lt;-glm(day_b~(.)^2,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}


summarize_all(diags,mean) </code></pre>
<pre><code>##         acc       sens      spec ppv  f1       auc
## 1 0.8124057 0.06468254 0.9633189 NaN NaN 0.5688129</code></pre>
<pre class="r"><code>#LASSO: 
library(glmnet)
responseforest&lt;-as.matrix(newdata$day_b) 
probsforest&lt;-model.matrix(fit2)[,-1] 


cv &lt;- cv.glmnet(probsforest,responseforest, family=&quot;binomial&quot;) 


{plot(cv$glmnet.fit, &quot;lambda&quot;, label=TRUE); abline(v = log(cv$lambda.1se)); abline(v = log(cv$lambda.min),lty=2)}</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cv &lt;- cv.glmnet(probsforest,responseforest, family=&quot;binomial&quot;)
lasso_fit&lt;-glmnet(probsforest,responseforest,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso_fit)</code></pre>
<pre><code>## 46 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                             s0
## (Intercept)          -1.611761
## X                     0.000000
## Y                     .       
## meanrain              .       
## meanISI               .       
## meantemp              .       
## meanRH                .       
## meanwind              .       
## meanlogarea           .       
## meanDC                .       
## X:Y                   .       
## X:meanrain            .       
## X:meanISI             .       
## X:meantemp            .       
## X:meanRH              .       
## X:meanwind            .       
## X:meanlogarea         .       
## X:meanDC              .       
## Y:meanrain            .       
## Y:meanISI             .       
## Y:meantemp            .       
## Y:meanRH              .       
## Y:meanwind            .       
## Y:meanlogarea         .       
## Y:meanDC              .       
## meanrain:meanISI      .       
## meanrain:meantemp     .       
## meanrain:meanRH       .       
## meanrain:meanwind     .       
## meanrain:meanlogarea  .       
## meanrain:meanDC       .       
## meanISI:meantemp      .       
## meanISI:meanRH        .       
## meanISI:meanwind      .       
## meanISI:meanlogarea   .       
## meanISI:meanDC        .       
## meantemp:meanRH       .       
## meantemp:meanwind     .       
## meantemp:meanlogarea  .       
## meantemp:meanDC       .       
## meanRH:meanwind       .       
## meanRH:meanlogarea    .       
## meanRH:meanDC         .       
## meanwind:meanlogarea  .       
## meanwind:meanDC       .       
## meanlogarea:meanDC    .</code></pre>
<pre class="r"><code>#10-fold cross validation on LASSO selected variables: 
set.seed(1234)
k=10 

data&lt;-newdata[sample(nrow(newdata)),] 
folds&lt;-cut(seq(1:nrow(newdata)),breaks=k,labels=F) 

diags&lt;-NULL
for(i in 1:k){
  
  train&lt;-newdata[folds!=i,] 
  test&lt;-newdata[folds==i,]
  truth&lt;-test$day_b
  
  
  fit&lt;-glm(day_b~X,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}


summarize_all(diags,mean) </code></pre>
<pre><code>##         acc sens spec ppv  f1       auc
## 1 0.8336727    0    1 NaN NaN 0.5199968</code></pre>
<p><em>I started with mean centering the rest of the numeric explanatory variables and creating a new dataset so that only the variables of interest were included. I ran a model predicting all numeric variables (X, Y, rain, ISI, temperature, relative humidity, wind, log area, and drought code) from the binary weekend or weekday predictor (1= weekend (Friday, Saturday, Sunday), 0 = weekday (Monday, Tuesday, Wednesday, Thursday)). The coefficients listed produced significant p-values: Y:meanwind (p = 0.038873), meanISI:meantemp ( p = 8.6e-05), meanISI:meanDC (p = 0.007206), and meanISI:meanRH (p = 0.037450). In-sample classification diagnostics were run for this model. The accurary is 0.8413926, the sensitivity is 0.1046512, the specificity is 0.9883991, the precision is 0.6428571, and the AUC is 0.7200939. The AUC shows that the model is predicting fairly well. True positive rate (sensitivity) is low again as it was in the last model and true negative rate is high as it was in the last model as well. This shows that the cutoff may be too high for the model.</em> <em>I did a 10-fold cross validation with the same model above and calculated new classification diagnostics for out of sample. The accuracy is slightly lower being 0.8124057, the sensitivity is slightly lower being 0.06468254, the specificity is slightly lower being 0.9633189, and the AUC is much lower being 0.5688129. This AUC shows that the model is definitely overfitting as it decreased by approximately 0.1512. This AUC means that the model is bad at predicting and is overfitting. Due to the overfitting, I ran a LASSO and found that the only variable kept in the LASSO was X. I will proceed to run a new cross-validation and model only predicting based on X. After running the model with only X as an explanatory variable through cross-validation and running a new model, the accuracy is higher than the last CV being 0.8336727, the sensitivity has gone to 0, the specificity has gone to 1, and the AUC is 0.5199968. The AUC has gotten even lower and does not predict the model really at all/is greatly overfitting. This could be due to many reasons such as failed assumptions due to correlated variables, bad data that is not specific enough to the response variable and has confounding variables, or that these explanatory variables do not statistically predict day of the week.</em></p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion:</h1>
<p><em>After thoroughly investigating the forest fire data, you can see that some of the variables may be highly correlated due to them being related to weather and fire conditions, leading to difficulty in predicting them in a model. Transformations may need to occur in order to have a well-fitted model that can predict out of sample conditions. In order for forest fires to be better predicted in the future, this analysis shows that mean temperature and mean wind have an interaction that significantly effects the mean log area of a forest fire. I would suggest that researchers look into this interaction in the future in order to better prepare communities for forest fires. Thank you to Paulo Cortez and Aniíbal Morais from the University of Minho in Portugal for allowing me to use your data, and making it available to the public for further analyses.</em></p>
</div>
